version: "2"
run:
  issues-exit-code: 1
  tests: true

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true

linters:
  enable:
    - bidichk                  # find dangerous bidi unicode symbols
    - bodyclose                # find unclosed http response bodies
    - dogsled                  # checks for too many ignored arguments
    - durationcheck            # verifies whether durations are multiplied, usually a mistake
    - err113                   # check error expressions
    - errorlint                # finds misuses of errors
    - gocritic                 # checks for style, performance issues, and common programming errors
    - godot                    # dots for everything
    - goprintffuncname         # checks that printf-like functions are named with `f` at the end
    - importas                 # verify that imports are consistent
    - makezero                 # verifies that slices use defaults
    - misspell                 # check spelling
    - nakedret                 # check for naked returns
    - nilerr                   # checks for misuses of `if err != nil { return nil }`
    - noctx                    # finds locations that should use context
    - revive                   # check standard linting rules
    - unconvert                # remove unnecessary conversions
    - usetesting               # ensure we use t.SetEnv instead of os.SetEnv
    - wastedassign             # finds assignments that are never used

  disable:
    - asciicheck               # non-ascii is allowed
    - containedctx             # gives false positives, however might be good to re-evaluate
    - contextcheck             # doesn't look like it's useful
    - cyclop                   # this complexity is not a good metric
    - decorder                 # not that useful
    - depguard                 # unused
    - dupl                     # slow
    - errchkjson               # false positives, checks for non-encodable json types
    - errname                  # we have different approach
    - exhaustive               # doesn't handle default case
    - forbidigo                # not useful
    - funlen                   # no limit on func length
    - gocognit                 # this complexity is not a good metric
    - goconst                  # check for things that could be replaced by constants
    - gocyclo                  # this complexity is not a good metric
    - godox                    # too many false positivies
    - goheader                 # separate tool
    - gomoddirectives          # not useful
    - gomodguard               # not useful
    - gosec                    # needs tweaking
    - grouper                  # we have a custom implementation
    - ireturn                  # not that useful for us
    - lll                      # don't need this check
    - maintidx                 # code complexity based on halsted V and cyclomatic, both shown to be ineffective
    - nlreturn                 # non-important code style
    - nolintlint               # checks that nolint directives are correct
    - paralleltest             # too many false positives
    - predeclared              # kind of useful, but not critical
    - promlinter               # not relevant
    - rowserrcheck             # checks if sql.Rows.Err is checked correctly - Disabled  because it reports false positive with defer statements after Query call
    - sqlclosecheck            # we have tagsql, which checks this better
    - staticcheck              # we already use staticcheck separately
    - tagliatelle              # not our style
    - testpackage              # sometimes it's useful to have tests on private funcs
    - thelper                  # too many false positives
    - tparallel                # false positivies
    - unused                   # part of staticcheck
    - varnamelen               # unenecssary
    - wrapcheck                # too much noise and false positives
    - wsl                      # too much noise

  settings:
    dupl:
      threshold: 150
    errcheck:
      check-type-assertions: false
      check-blank: false
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - ifElseChain
    gocyclo:
      min-complexity: 10
    lll:
      line-length: 140
      tab-width: 1
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - err113
        text: do not define dynamic errors
      - linters: # uninteresting, it would be nice to be consistent, but we don't want to block the build for it
          - revive
        text: if-return
      - linters: # a lot of false-positives for c exports
          - revive
        text: var-naming
      - linters: # uninteresting, error doesn't need to be the last type
          - revive
        text: error-return
      - linters: # uninteresting, ideally we would have this on, but we need to fix all the packages first
          - revive
        text: package-comments
      - linters: # uninteresting, it would be nice to be consistent, but we don't want to block the build for it
          - revive
        text: superfluous-else
      - linters: # uninteresting, it would be nice to be consistent, but we don't want to block the build for it
          - revive
        text: indent-error-flow
      - linters: # uninteresting, it's common to leave args unused
          - revive
        text: unused-parameter
      - linters: # false positives, see https://github.com/mgechev/revive/issues/810
          - revive
        text: empty-block
      - linters: # uninteresting, it's fine to redefine builtins
          - revive
        text: redefines-builtin-id
    paths:
      - .*\.pb\.go$
      - .*\.dbx\.go$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - .*\.dbx\.go$
      - third_party$
      - builtin$
      - examples$
