// Copyright (C) 2019 Storj Labs, Inc.
// See LICENSE for copying information.

package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/zeebo/errs"
)

var checkFiles = map[string]bool{
	".go":  true,
	".ts":  true,
	".js":  true,
	".vue": true,
}

// MissingCopyright error means that check was successful but header is missing.
var MissingCopyright = errs.Class("missing copyright")

// Fix is a flag to try fixing missing headers.
var Fix = flag.Bool("fix", false, "Fix violations, if possible")

func main() {
	flag.Parse()
	cmd := exec.Command("git", "ls-files")
	out, err := cmd.Output()
	if err != nil {
		fmt.Fprintf(os.Stderr, "running \"git ls-files\" failed:\n")
		fmt.Fprintf(os.Stderr, "\t%v\n", err)
		os.Exit(1)
	}

	var failed int
	committedFiles := strings.Split(string(out), "\n")
	for _, path := range committedFiles {
		if path == "" {
			continue
		}

		if !checkFiles[filepath.Ext(path)] {
			continue
		}

		err := checkCopyright(path)
		if MissingCopyright.Has(err) && *Fix {
			err := fixCopyright(path)
			if err != nil {
				failed++
				fmt.Fprintf(os.Stderr, "%v\n", err)
			}
		} else if err != nil {
			failed++
			fmt.Fprintf(os.Stderr, "%v\n", err)
		}
	}

	if failed > 0 {
		os.Exit(1)
	}
}

func fixCopyright(path string) error {
	f, err := ioutil.ReadFile(path)
	if err != nil {
		return errs.Wrap(err)
	}

	stat, err := os.Stat(path)
	if err != nil {
		return errs.Wrap(err)
	}
	switch filepath.Ext(path) {
	case ".go", ".ts", ".js", ".vue":
		f = append([]byte(fmt.Sprintf("// Copyright (C) %d Storj Labs, Inc.\n// See LICENSE for copying information.\n\n", time.Now().Year())), f...)
	default:
		fmt.Fprintf(os.Stderr, "WARNING: copyright fix is not supported for file type: %s", path)
	}
	return ioutil.WriteFile(path, f, stat.Mode())
}

func checkCopyright(path string) error {
	file, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("failed to read %v: %w", path, err)
	}
	defer func() { _ = file.Close() }()

	var header [256]byte
	n, err := file.Read(header[:])
	if errors.Is(err, io.EOF) {
		err = nil
	}
	if err != nil {
		return fmt.Errorf("failed to read %v: %w", path, err)
	}

	isGenerated := bytes.Contains(header[:n], []byte(`AUTOGENERATED`)) ||
		bytes.Contains(header[:n], []byte(`Code generated`)) ||
		bytes.Contains(header[:n], []byte(`Autogenerated`))
	if isGenerated {
		return nil
	}

	if bytes.Contains(header[:n], []byte(`Copyright `)) {
		return nil
	}
	return MissingCopyright.New("missing copyright %v", path)
}
